name: Checks

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        # actions/checkout v7.0.1
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Set up Python
        # actions/setup-python v7.0.0
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: "3.14"
      - name: Set up just
        # extractions/setup-just v4
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3
        with:
          just-version: "1.58.0"
      - name: Set up development environment
        run: just setup
      - name: Run repository checks
        run: just check
